<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'HP Probook 430 G5',
                'img' => 'p1.png',
                'gallery' => ['p1-0.jpg', 'p1-1.jpg', 'p1-2.jpg', 'p1-3.jpg', 'p1-4.jpg'],
                'specs' => 'i5 8th | 8/256 | 13.3"',
                'price' => 2300.00,
                'description' => 'HP Probook 430 G5 - bon compromis performance/autonomie.',
            ],
            [
                'name' => 'HP Elitebook 840 G7',
                'img' => 'p2.jpg',
                'gallery' => ['p2-0.jpg', 'p2-1.jpg', 'p2-2.jpg', 'p2-3.jpg', 'p2-4.jpg'],
                'specs' => 'i7 10th | 16/256 | 14"',
                'price' => 4200.00,
                'description' => 'HP Elitebook 840 G7 - mobilité premium pour le travail.',
            ],
            [
                'name' => 'HP Elitebook 830 G8',
                'img' => 'p3.jpg',
                'gallery' => ['p3-1.jpg', 'p3-2.jpg', 'p3-3.jpg', 'p3-4.jpg', 'p3-5.jpg'],
                'specs' => 'i7 11th | 16/512 | 13.3"',
                'price' => 4500.00,
                'description' => 'HP Elitebook 830 G8 - puissant et compact.',
            ],
            [
                'name' => 'HP Probook 430 G6',
                'img' => 'p4.jpg',
                'gallery' => ['p4-1.jpg', 'p4-2.jpg', 'p4-3.jpg'],
                'specs' => 'i5 8th | 8/256 | 13.3"',
                'price' => 2300.00,
                'description' => 'HP Probook 430 G6 - fiable pour études et bureautique.',
            ],
            [
                'name' => 'Dell Latitude 5410',
                'img' => 'p5.jpg',
                'gallery' => [ 'p5-2.jpg'],
                'specs' => 'i5 10th | 16/256 | 14"',
                'price' => 2900.00,
                'description' => 'Dell Latitude 5410 - conçu pour la productivité au quotidien.',
            ],
            [
                'name' => 'Dell Inspiron 7786',
                'img' => 'p6.jpg',
                'gallery' => ['p6-1.jpg', 'p6-2.jpg', 'p6-3.jpg', 'p6-4.jpg'],
                'specs' => 'i7 8th | 16GB | 1TB SSD | 17"',
                'price' => 4000.00,
                'description' => 'Dell Inspiron 7786 - puissant pour multitâche et stockage.',
            ],
            [
                'name' => 'HP Elitebook 840 G9',
                'img' => 'p7.jpg',
                'gallery' => ['p7-1.jpg', 'p7-2.jpg'],
                'specs' => 'i7 12th | 16/512 | 14"',
                'price' => 7300.00,
                'description' => 'HP Elitebook 840 G9 - performances de dernière génération.',
            ],
            [
                'name' => 'HP Probook 430 G6 i3',
                'img' => 'p8.jpg',
                'gallery' => ['p8-1.jpg', 'p8-2.jpg', 'p8-3.jpg', 'p8-4.jpg'],
                'specs' => 'i3 8th | 8/128 | 13"',
                'price' => 1850.00,
                'description' => 'HP Probook 430 G6 i3 - entrée de gamme efficace.',
            ],
            [
                'name' => 'HP Elitebook 830 G8 i5',
                'img' => 'p9.jpg',
                'gallery' => ['p9-1.jpg', 'p9-2.jpg', 'p9-3.jpg'],
                'specs' => 'i5 11th | 8/256 | 13.3"',
                'price' => 2800.00,
                'description' => 'HP Elitebook 830 G8 i5 - équilibre entre performance et budget.',
            ],
            [
                'name' => 'HP Probook 430 G5',
                'img' => 'p10.jpg',
                'gallery' => ['p10-1.jpg', 'p10-2.jpg', 'p10-3.jpg', 'p10-4.jpg'],
                'specs' => 'i5 8th | 8/256 | 13.3"',
                'price' => 2250.00,
                'description' => 'HP Probook 430 G5 - pratique pour le travail et les études.',
            ],
            [
                'name' => 'HP Elitebook 840 G4',
                'img' => 'p11.jpg',
                'gallery' => ['p11-1.jpg', 'p11-2.jpg', 'p11-3.jpg'],
                'specs' => 'i7 7th | 8/256 | 14"',
                'price' => 2200.00,
                'description' => 'HP Elitebook 840 G4 - performance et fiabilité.',
            ],
            [
                'name' => 'HP Elitebook 840 G5',
                'img' => 'p12.jpg',
                'gallery' => ['p12-1.jpg', 'p12-2.jpg', 'p12-3.jpg'],
                'specs' => 'i7 8th | 16/256 | 14"',
                'price' => 3200.00,
                'description' => 'HP Elitebook 840 G5 - élégance et puissance.',
            ],
            [
                'name' => 'HP Elitebook 830 G6',
                'img' => 'p13.jpg',
                'gallery' => ['p13-1.jpg', 'p13-2.jpg', 'p13-3.jpg'],
                'specs' => 'i7 8th | 16/256 | 13.3"',
                'price' => 3200.00,
                'description' => 'HP Elitebook 830 G6 - compact et performant.',
            ],
            [
                'name' => 'HP Elitebook 830 G6 i5',
                'img' => 'p14.jpg',
                'gallery' => ['p14-1.jpg', 'p14-2.jpg', 'p14-3.jpg'],
                'specs' => 'i5 8th | 8/256 | 13.3"',
                'price' => 2500.00,
                'description' => 'HP Elitebook 830 G6 i5 - idéal pour la mobilité.',
            ],
            [
                'name' => 'Lenovo ThinkPad X270',
                'img' => 'p15.jpg',
                'gallery' => ['p15-1.jpg', 'p15-2.jpg', 'p15-3.jpg', 'p15-4.jpg'],
                'specs' => 'i5 6th | 8/128 | 12.5"',
                'price' => 1800.00,
                'description' => 'Lenovo ThinkPad X270 - ultra portable et robuste.',
            ],
            [
                'name' => 'HP Elitebook 830 G5',
                'img' => 'p16.jpg',
                'gallery' => ['p16-1.jpg', 'p16-2.jpg', 'p16-3.jpg'],
                'specs' => 'i7 8th | 16/256 | 13.3"',
                'price' => 3300.00,
                'description' => 'HP Elitebook 830 G5 - excellence professionnelle.',
            ],
            [
                'name' => 'Dell Latitude 5320',
                'img' => 'p17.jpg',
                'gallery' => ['p17-1.jpg', 'p17-2.jpg', 'p17-3.jpg', 'p17-4.jpg'],
                'specs' => 'i5 11th | 16/256 | 13.3"',
                'price' => 3300.00,
                'description' => 'Dell Latitude 5320 - moderne et efficace.',
            ],
            [
                'name' => 'HP Elitebook 840 G4 i5',
                'img' => 'p18.jpg',
                'gallery' => ['p18-1.jpg', 'p18-2.jpg', 'p18-3.jpg'],
                'specs' => 'i5 7th | 8/256 | 14"',
                'price' => 2200.00,
                'description' => 'HP Elitebook 840 G4 i5 - rapport qualité/prix.',
            ],
            [
                'name' => 'HP Elitebook 840 G6',
                'img' => 'p19.jpg',
                'gallery' => ['p19-1.jpg', 'p19-2.jpg', 'p19-3.jpg'],
                'specs' => 'i7 8th | 16/512 | 14"',
                'price' => 3500.00,
                'description' => 'HP Elitebook 840 G6 - stockage généreux.',
            ],
            [
                'name' => 'HP Elitebook 840 G6 i5',
                'img' => 'p20.jpg',
                'gallery' => ['p20-1.jpg', 'p20-2.jpg', 'p20-3.jpg'],
                'specs' => 'i5 8th | 8/256 | 14"',
                'price' => 2700.00,
                'description' => 'HP Elitebook 840 G6 i5 - équilibre parfait.',
            ],
            [
                'name' => 'Dell Latitude 3520',
                'img' => 'p21.jpg',
                'gallery' => ['p21-1.jpg', 'p21-2.jpg', 'p21-3.jpg', 'p21-4.jpg', 'p21-5.jpg'],
                'specs' => 'i5 11th | 16/256 | 15"',
                'price' => 3000.00,
                'description' => 'Dell Latitude 3520 - grand écran confortable.',
            ],
            [
                'name' => 'HP Elitebook 830 G7 x360',
                'img' => 'p22.jpg',
                'gallery' => ['p22-1.jpg', 'p22-2.jpg', 'p22-3.jpg', 'p22-4.jpg'],
                'specs' => 'i5 10th | 16/256 | tactile | 13.3"',
                'price' => 3800.00,
                'description' => 'HP Elitebook 830 G7 x360 - convertible tactile.',
            ],
            [
                'name' => 'Dell Latitude 5470',
                'img' => 'p23.jpg',
                'gallery' => ['p23-1.jpg', 'p23-2.jpg', 'p23-3.jpg', 'p23-4.jpg', 'p23-5.jpg'],
                'specs' => 'i7 6th HQ | 8/256 | 14"',
                'price' => 2500.00,
                'description' => 'Dell Latitude 5470 - processeur haute performance.',
            ],
            [
                'name' => 'HP Elitebook 1030 G7',
                'img' => 'p24.jpg',
                'gallery' => ['p24-1.jpg', 'p24-2.jpg', 'p24-3.jpg'],
                'specs' => 'i5 10th | 16/512 | tactile x360 | 13"',
                'price' => 4200.00,
                'description' => 'HP Elitebook 1030 G7 - luxe et polyvalence.',
            ],
            [
                'name' => 'Dell Latitude 5420',
                'img' => 'p25.jpg',
                'gallery' => ['p25-1.jpg', 'p25-2.jpg', 'p25-3.jpg', 'p25-4.jpg', 'p25-5.jpg'],
                'specs' => 'i5 11th | 8/256 | 14"',
                'price' => 2750.00,
                'description' => 'Dell Latitude 5420 - productivité assurée.',
            ],
            [
                'name' => 'HP Elitebook 1030 G2',
                'img' => 'p26.jpg',
                'gallery' => ['p26-1.jpg', 'p26-2.jpg', 'p26-3.jpg'],
                'specs' => 'i5 7th | 8/256 | tactile x360 | 13.3"',
                'price' => 2700.00,
                'description' => 'HP Elitebook 1030 G2 - convertible élégant.',
            ],
            [
                'name' => 'Dell Latitude 7300',
                'img' => 'p27.jpg',
                'gallery' => ['p27-1.jpg', 'p27-2.jpg', 'p27-3.jpg', 'p27-4.jpg'],
                'specs' => 'i7 8th | 16/256 | 13.3"',
                'price' => 3000.00,
                'description' => 'Dell Latitude 7300 - gamme premium.',
            ],
            [
                'name' => 'HP Probook 430 G5 i3',
                'img' => 'p28.jpg',
                'gallery' => ['p28-1.jpg', 'p28-2.jpg', 'p28-3.jpg'],
                'specs' => 'i3 7th | 8/128 | 13"',
                'price' => 1700.00,
                'description' => 'HP Probook 430 G5 i3 - entrée de gamme accessible.',
            ],
            [
                'name' => 'HP Elitebook 830 G8 i7',
                'img' => 'p29.jpg',
                'gallery' => ['p29-1.jpg', 'p29-2.jpg', 'p29-3.jpg'],
                'specs' => 'i7 11th | 16/512 | 13.3"',
                'price' => 4500.00,
                'description' => 'HP Elitebook 830 G8 i7 - haute performance.',
            ],
            [
                'name' => 'Dell Latitude 5400',
                'img' => 'p30.jpg',
                'gallery' => ['p30-1.jpg', 'p30-2.jpg', 'p30-3.jpg'],
                'specs' => 'i7 8th | 8/256 | 14"',
                'price' => 2800.00,
                'description' => 'Dell Latitude 5400 - fiable et endurant.',
            ],
            [
                'name' => 'HP Elitebook 1030 G8',
                'img' => 'p31.jpg',
                'gallery' => ['p31-1.jpg', 'p31-2.jpg', 'p31-3.jpg'],
                'specs' => 'i5 11th | 16/256 | tactile x360 | 13.3"',
                'price' => 4500.00,
                'description' => 'HP Elitebook 1030 G8 - dernier cri tactile.',
            ],
            [
                'name' => 'Lenovo ThinkPad E470',
                'img' => 'p32.jpg',
                'gallery' => ['p32-1.jpg', 'p32-2.jpg', 'p32-3.jpg'],
                'specs' => 'i5 7th | 8/256 | double GPU | 14"',
                'price' => 2450.00,
                'description' => 'Lenovo ThinkPad E470 - double carte graphique.',
            ],
            [
                'name' => 'Lenovo V330',
                'img' => 'p33.jpg',
                'gallery' => ['p33-1.jpg', 'p33-2.jpg', 'p33-3.jpg', 'p33-4.jpg'],
                'specs' => 'i5 8th | 8/256 | 14"',
                'price' => 2400.00,
                'description' => 'Lenovo V330 - simplicité et efficacité.',
            ],
        ];

        foreach ($products as $data) {
            Product::updateOrCreate(
                ['name' => $data['name']],
                $data
            );
        }
    }
}